# 101 Numpy Exercises

### https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.18.4


In [8]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.full((3,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [14]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [17]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [23]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
out = np.where(arr % 2 == 1, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [26]:
np.reshape(arr, (2, -1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [29]:
a + b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
np.concatenate((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [39]:
np.concatenate((a,b),axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [40]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [41]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [50]:
a[a == b]

array([2, 2, 4, 4])

In [51]:
np.intersect1d(a,b)

array([2, 4])

In [57]:
#remove elements of b from a
np.setdiff1d(a,b)

array([1, 3, 5, 6])

In [59]:
# gives indexes where elements match
np.where(a == b)

(array([1, 3, 5, 7]),)

In [62]:
# number between 5 and 10 incl

a[(a >= 5) & (a <= 10)]

array([5, 6])

In [65]:
# 15